// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SHTL.Modules.Infrastructure.Persistence;

#nullable disable

namespace SHTL.Modules.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508195103_AddDocumentDefaultFieldColumns")]
    partial class AddDocumentDefaultFieldColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Acc.AccRolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("permission_code");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_acc_role_permissions");

                    b.ToTable("acc_role_permissions", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Acc.Dept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("describe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Parent")
                        .HasColumnType("int")
                        .HasColumnName("parent");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("Parents")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parents");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_acc_depts");

                    b.ToTable("acc_depts", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Acc.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("module_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Parent")
                        .HasColumnType("int")
                        .HasColumnName("parent");

                    b.Property<string>("Parents")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parents");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_acc_roles");

                    b.ToTable("acc_roles", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Acc.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_acc_users");

                    b.ToTable("acc_users", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Acc.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_acc_user_roles");

                    b.ToTable("acc_user_roles", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Cnf.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountLimit")
                        .HasColumnType("int")
                        .HasColumnName("account_limit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("describe");

                    b.Property<long>("DocumentLimit")
                        .HasColumnType("bigint")
                        .HasColumnName("document_limit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("is_published");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lang");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Parent")
                        .HasColumnType("int")
                        .HasColumnName("parent");

                    b.Property<string>("Parents")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parents");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<long>("StorageLimit")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_limit");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_cnf_channels");

                    b.ToTable("cnf_channels", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Cnf.CnfConfigEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("group_name");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_cnf_configs");

                    b.ToTable("cnf_configs", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Cnf.CnfSeparateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cnf_separate_types");

                    b.ToTable("cnf_separate_types", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Cnf.ContentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("describe");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDocType")
                        .HasColumnType("bit")
                        .HasColumnName("is_doc_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_cnf_content_types");

                    b.ToTable("cnf_content_types", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Cnf.RecordType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("describe");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_cnf_record_types");

                    b.ToTable("cnf_record_types", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Cnf.SyncType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("describe");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_cnf_sync_types");

                    b.ToTable("cnf_sync_types", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Log.AccessLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int")
                        .HasColumnName("status_code");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_log_access_logs");

                    b.ToTable("log_access_logs", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Log.ActionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<string>("RecordId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("table_name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_log_action_logs");

                    b.ToTable("log_action_logs", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Log.ErrorLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stack_trace");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_log_error_logs");

                    b.ToTable("log_error_logs", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("author");

                    b.Property<string>("BoxNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("box_no");

                    b.Property<DateTime?>("Checked1At")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked1at");

                    b.Property<int>("Checked1By")
                        .HasColumnType("int")
                        .HasColumnName("checked1by");

                    b.Property<byte>("Checked1Result")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked1result");

                    b.Property<int>("Checked1ReturnCount")
                        .HasColumnType("int")
                        .HasColumnName("checked1return_count");

                    b.Property<string>("Checked1ReturnReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("checked1return_reason");

                    b.Property<DateTime?>("Checked2At")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked2at");

                    b.Property<int>("Checked2By")
                        .HasColumnType("int")
                        .HasColumnName("checked2by");

                    b.Property<byte>("Checked2Result")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked2result");

                    b.Property<string>("Checked2ReturnReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("checked2return_reason");

                    b.Property<DateTime?>("CheckedFinalAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked_final_at");

                    b.Property<int>("CheckedFinalBy")
                        .HasColumnType("int")
                        .HasColumnName("checked_final_by");

                    b.Property<string>("CheckedFinalChangeInfo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("checked_final_change_info");

                    b.Property<byte>("CheckedFinalResult")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked_final_result");

                    b.Property<DateTime?>("CheckedLogicAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked_logic_at");

                    b.Property<int>("CheckedLogicBy")
                        .HasColumnType("int")
                        .HasColumnName("checked_logic_by");

                    b.Property<byte>("CheckedLogicResult")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked_logic_result");

                    b.Property<DateTime?>("CheckedScan1At")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked_scan1at");

                    b.Property<int>("CheckedScan1By")
                        .HasColumnType("int")
                        .HasColumnName("checked_scan1by");

                    b.Property<byte>("CheckedScan1Result")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked_scan1result");

                    b.Property<DateTime?>("CheckedScan2At")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked_scan2at");

                    b.Property<int>("CheckedScan2By")
                        .HasColumnType("int")
                        .HasColumnName("checked_scan2by");

                    b.Property<byte>("CheckedScan2Result")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked_scan2result");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("content_type_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<byte>("CurrentStep")
                        .HasColumnType("tinyint")
                        .HasColumnName("current_step");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("describe");

                    b.Property<int>("DocTypeId")
                        .HasColumnType("int")
                        .HasColumnName("doc_type_id");

                    b.Property<long>("ExcelMetadataId")
                        .HasColumnType("bigint")
                        .HasColumnName("excel_metadata_id");

                    b.Property<byte>("ExportStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("export_status");

                    b.Property<DateTime?>("ExportedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("exported_at");

                    b.Property<int>("ExportedBy")
                        .HasColumnType("int")
                        .HasColumnName("exported_by");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extension");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("extracted_at");

                    b.Property<int>("ExtractedBy")
                        .HasColumnType("int")
                        .HasColumnName("extracted_by");

                    b.Property<byte>("ExtractedResult")
                        .HasColumnType("tinyint")
                        .HasColumnName("extracted_result");

                    b.Property<int>("ExtractedReturnCount")
                        .HasColumnType("int")
                        .HasColumnName("extracted_return_count");

                    b.Property<string>("ExtractedReturnReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extracted_return_reason");

                    b.Property<string>("Field1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field1");

                    b.Property<string>("Field10")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field10");

                    b.Property<string>("Field11")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field11");

                    b.Property<string>("Field12")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field12");

                    b.Property<string>("Field13")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field13");

                    b.Property<string>("Field14")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field14");

                    b.Property<string>("Field15")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field15");

                    b.Property<long?>("Field16")
                        .HasColumnType("bigint")
                        .HasColumnName("field16");

                    b.Property<long?>("Field17")
                        .HasColumnType("bigint")
                        .HasColumnName("field17");

                    b.Property<long?>("Field18")
                        .HasColumnType("bigint")
                        .HasColumnName("field18");

                    b.Property<long?>("Field19")
                        .HasColumnType("bigint")
                        .HasColumnName("field19");

                    b.Property<string>("Field2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field2");

                    b.Property<long?>("Field20")
                        .HasColumnType("bigint")
                        .HasColumnName("field20");

                    b.Property<DateTime?>("Field21")
                        .HasColumnType("datetime2")
                        .HasColumnName("field21");

                    b.Property<DateTime?>("Field22")
                        .HasColumnType("datetime2")
                        .HasColumnName("field22");

                    b.Property<decimal?>("Field23")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("field23");

                    b.Property<decimal?>("Field24")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("field24");

                    b.Property<decimal?>("Field25")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("field25");

                    b.Property<string>("Field3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field3");

                    b.Property<string>("Field4")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field4");

                    b.Property<string>("Field5")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field5");

                    b.Property<string>("Field6")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field6");

                    b.Property<string>("Field7")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field7");

                    b.Property<string>("Field8")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field8");

                    b.Property<string>("Field9")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field9");

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<long>("FolderId")
                        .HasColumnType("bigint")
                        .HasColumnName("folder_id");

                    b.Property<bool>("IsChecked1")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked1");

                    b.Property<bool>("IsChecked2")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked2");

                    b.Property<bool>("IsCheckedFinal")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked_final");

                    b.Property<bool>("IsCheckedLogic")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked_logic");

                    b.Property<bool>("IsCheckedScan1")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked_scan1");

                    b.Property<bool>("IsCheckedScan2")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked_scan2");

                    b.Property<bool>("IsColorScan")
                        .HasColumnType("bit")
                        .HasColumnName("is_color_scan");

                    b.Property<bool>("IsExtracted")
                        .HasColumnType("bit")
                        .HasColumnName("is_extracted");

                    b.Property<bool>("IsOcrEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_ocr_enabled");

                    b.Property<bool>("IsZoned")
                        .HasColumnType("bit")
                        .HasColumnName("is_zoned");

                    b.Property<DateTime?>("Issued")
                        .HasColumnType("datetime2")
                        .HasColumnName("issued");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("issued_by");

                    b.Property<int?>("IssuedYear")
                        .HasColumnType("int")
                        .HasColumnName("issued_year");

                    b.Property<string>("LevelNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("level_no");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("locked_at");

                    b.Property<byte>("LockedByStep")
                        .HasColumnType("tinyint")
                        .HasColumnName("locked_by_step");

                    b.Property<int>("LockedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("locked_by_user_id");

                    b.Property<double>("MaxDpi")
                        .HasColumnType("float")
                        .HasColumnName("max_dpi");

                    b.Property<double>("MinDpi")
                        .HasColumnType("float")
                        .HasColumnName("min_dpi");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Noted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noted");

                    b.Property<DateTime?>("OcrAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ocr_at");

                    b.Property<int>("OcrBy")
                        .HasColumnType("int")
                        .HasColumnName("ocr_by");

                    b.Property<byte>("OcrResult")
                        .HasColumnType("tinyint")
                        .HasColumnName("ocr_result");

                    b.Property<byte>("OcrStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("ocr_status");

                    b.Property<int>("PageCount")
                        .HasColumnType("int")
                        .HasColumnName("page_count");

                    b.Property<int>("PageCountA0")
                        .HasColumnType("int")
                        .HasColumnName("page_count_a0");

                    b.Property<int>("PageCountA1")
                        .HasColumnType("int")
                        .HasColumnName("page_count_a1");

                    b.Property<int>("PageCountA2")
                        .HasColumnType("int")
                        .HasColumnName("page_count_a2");

                    b.Property<int>("PageCountA3")
                        .HasColumnType("int")
                        .HasColumnName("page_count_a3");

                    b.Property<int>("PageCountA4")
                        .HasColumnType("int")
                        .HasColumnName("page_count_a4");

                    b.Property<int>("PageCountOther")
                        .HasColumnType("int")
                        .HasColumnName("page_count_other");

                    b.Property<string>("PathConverted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path_converted");

                    b.Property<string>("PathOriginal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path_original");

                    b.Property<string>("PathPdfSearchable")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path_pdf_searchable");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("poster");

                    b.Property<string>("Receiver")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receiver");

                    b.Property<string>("RecordNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("record_no");

                    b.Property<string>("RecordTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("record_title");

                    b.Property<int>("RecordTypeId")
                        .HasColumnType("int")
                        .HasColumnName("record_type_id");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<string>("ShelfNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shelf_no");

                    b.Property<string>("Signer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("signer");

                    b.Property<string>("SlotNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slot_no");

                    b.Property<string>("SortMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sort_meta");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subject");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<string>("SymbolNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symbol_no");

                    b.Property<int>("SyncTypeId")
                        .HasColumnType("int")
                        .HasColumnName("sync_type_id");

                    b.Property<string>("ThumbPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thumb_path");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<string>("VersionPdf")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("version_pdf");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.Property<string>("WorkstationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("workstation_name");

                    b.Property<DateTime?>("ZonedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("zoned_at");

                    b.Property<int>("ZonedBy")
                        .HasColumnType("int")
                        .HasColumnName("zoned_by");

                    b.Property<byte>("ZonedResult")
                        .HasColumnType("tinyint")
                        .HasColumnName("zoned_result");

                    b.HasKey("Id")
                        .HasName("pk_stg_documents");

                    b.ToTable("stg_documents", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.DocumentPage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    b.Property<int>("DpiX")
                        .HasColumnType("int")
                        .HasColumnName("dpi_x");

                    b.Property<int>("DpiY")
                        .HasColumnType("int")
                        .HasColumnName("dpi_y");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int")
                        .HasColumnName("page_number");

                    b.Property<string>("PageSize")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("page_size");

                    b.HasKey("Id")
                        .HasName("pk_stg_doc_sohoa_page");

                    b.ToTable("stg_doc_sohoa_page", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.ExportJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompressedPercent")
                        .HasColumnType("int")
                        .HasColumnName("compressed_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<int>("DocStatus")
                        .HasColumnType("int")
                        .HasColumnName("doc_status");

                    b.Property<string>("DownloadLogPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("download_log_path");

                    b.Property<string>("DownloadPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("download_path");

                    b.Property<int>("Error")
                        .HasColumnType("int")
                        .HasColumnName("error");

                    b.Property<string>("ExportInputJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("export_input_json");

                    b.Property<int>("ExportTypeId")
                        .HasColumnType("int")
                        .HasColumnName("export_type_id");

                    b.Property<int>("FieldFolderExport")
                        .HasColumnType("int")
                        .HasColumnName("field_folder_export");

                    b.Property<string>("FilterJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("filter_json");

                    b.Property<bool>("IsExportFile")
                        .HasColumnType("bit")
                        .HasColumnName("is_export_file");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Processed")
                        .HasColumnType("int")
                        .HasColumnName("processed");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_at");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int")
                        .HasColumnName("requested_by");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<int>("Success")
                        .HasColumnType("int")
                        .HasColumnName("success");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_stg_export_jobs");

                    b.ToTable("stg_export_jobs", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.ExportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ExcelFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("excel_file_name");

                    b.Property<string>("ExcelFilePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("excel_file_path");

                    b.Property<string>("ExporterClass")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("exporter_class");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("JsonConfig")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("json_config");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_cnf_export_types");

                    b.ToTable("cnf_export_types", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.FormCell", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Cell")
                        .HasColumnType("int")
                        .HasColumnName("cell");

                    b.Property<int>("CellType")
                        .HasColumnType("int")
                        .HasColumnName("cell_type");

                    b.Property<DateTime?>("Checked1At")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked1_at");

                    b.Property<int>("Checked1By")
                        .HasColumnType("int")
                        .HasColumnName("checked1_by");

                    b.Property<byte>("Checked1Result")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked1_result");

                    b.Property<string>("Checked1Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("checked1_value");

                    b.Property<DateTime?>("Checked2At")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked2_at");

                    b.Property<int>("Checked2By")
                        .HasColumnType("int")
                        .HasColumnName("checked2_by");

                    b.Property<byte>("Checked2Result")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked2_result");

                    b.Property<string>("Checked2Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("checked2_value");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CroppedPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cropped_path");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("district");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("extracted_at");

                    b.Property<int>("ExtractedBy")
                        .HasColumnType("int")
                        .HasColumnName("extracted_by");

                    b.Property<byte>("ExtractedResult")
                        .HasColumnType("tinyint")
                        .HasColumnName("extracted_result");

                    b.Property<string>("ExtractedValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extracted_value");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field");

                    b.Property<string>("GroupCell")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("group_cell");

                    b.Property<int>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<bool>("IsValueDiff1")
                        .HasColumnType("bit")
                        .HasColumnName("is_value_diff1");

                    b.Property<bool>("IsValueDiff2")
                        .HasColumnType("bit")
                        .HasColumnName("is_value_diff2");

                    b.Property<int>("Page")
                        .HasColumnType("int")
                        .HasColumnName("page");

                    b.Property<int>("PageHeight")
                        .HasColumnType("int")
                        .HasColumnName("page_height");

                    b.Property<int>("PageWidth")
                        .HasColumnType("int")
                        .HasColumnName("page_width");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ward");

                    b.Property<int>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_stg_form_cells");

                    b.ToTable("stg_form_cells", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.OcrJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_stg_ocr_jobs");

                    b.ToTable("stg_ocr_jobs", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.StgCategoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_stg_category_types");

                    b.ToTable("stg_category_types", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.StgDocField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CClass")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_class");

                    b.Property<int>("Datatype")
                        .HasColumnType("int")
                        .HasColumnName("datatype");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRecord")
                        .HasColumnType("bit")
                        .HasColumnName("is_record");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_stg_doc_fields");

                    b.ToTable("stg_doc_fields", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.StgDocFieldGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("group_name");

                    b.Property<int>("IdParent")
                        .HasColumnType("int")
                        .HasColumnName("id_parent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_stg_doc_field_groups");

                    b.ToTable("stg_doc_field_groups", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.StgDocFieldSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FixValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fix_value");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("format");

                    b.Property<int>("ICol")
                        .HasColumnType("int")
                        .HasColumnName("i_col");

                    b.Property<int>("IRow")
                        .HasColumnType("int")
                        .HasColumnName("i_row");

                    b.Property<int>("IType")
                        .HasColumnType("int")
                        .HasColumnName("i_type");

                    b.Property<int>("IdCategoryType")
                        .HasColumnType("int")
                        .HasColumnName("id_category_type");

                    b.Property<int>("IdField")
                        .HasColumnType("int")
                        .HasColumnName("id_field");

                    b.Property<int>("IdFieldGroup")
                        .HasColumnType("int")
                        .HasColumnName("id_field_group");

                    b.Property<int>("IdPatternType")
                        .HasColumnType("int")
                        .HasColumnName("id_pattern_type");

                    b.Property<int>("IdType")
                        .HasColumnType("int")
                        .HasColumnName("id_type");

                    b.Property<bool>("IsCapitalize")
                        .HasColumnType("bit")
                        .HasColumnName("is_capitalize");

                    b.Property<bool>("IsCatalog")
                        .HasColumnType("bit")
                        .HasColumnName("is_catalog");

                    b.Property<bool>("IsCatalogMain")
                        .HasColumnType("bit")
                        .HasColumnName("is_catalog_main");

                    b.Property<bool>("IsMulti")
                        .HasColumnType("bit")
                        .HasColumnName("is_multi");

                    b.Property<bool>("IsOcrFix")
                        .HasColumnType("bit")
                        .HasColumnName("is_ocr_fix");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit")
                        .HasColumnName("is_read_only");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearch")
                        .HasColumnType("bit")
                        .HasColumnName("is_search");

                    b.Property<bool>("IsUpperCase")
                        .HasColumnType("bit")
                        .HasColumnName("is_upper_case");

                    b.Property<int>("MaxLen")
                        .HasColumnType("int")
                        .HasColumnName("max_len");

                    b.Property<string>("MaxValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("max_value");

                    b.Property<int>("MinLen")
                        .HasColumnType("int")
                        .HasColumnName("min_len");

                    b.Property<string>("MinValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("min_value");

                    b.Property<int>("OcrType")
                        .HasColumnType("int")
                        .HasColumnName("ocr_type");

                    b.Property<string>("PatternCustom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pattern_custom");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_stg_doc_field_settings");

                    b.ToTable("stg_doc_field_settings", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.StgDocSoHoaOcrFix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Excepts")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("excepts");

                    b.Property<int>("FromPosition")
                        .HasColumnType("int")
                        .HasColumnName("from_position");

                    b.Property<string>("FromStr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("from_str");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("ToPosition")
                        .HasColumnType("int")
                        .HasColumnName("to_position");

                    b.Property<string>("ToStr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("to_str");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_stg_doc_sohoa_ocr_fixes");

                    b.ToTable("stg_doc_sohoa_ocr_fixes", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.StgDocSoHoaOcrFixType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.HasKey("Id")
                        .HasName("pk_stg_doc_sohoa_ocr_fix_types");

                    b.ToTable("stg_doc_sohoa_ocr_fix_types", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.StgDocType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("describe");

                    b.Property<int>("ExtractorTypeId")
                        .HasColumnType("int")
                        .HasColumnName("extractor_type_id");

                    b.Property<int>("FieldQuantity")
                        .HasColumnType("int")
                        .HasColumnName("field_quantity");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsOcrManualZoned")
                        .HasColumnType("bit")
                        .HasColumnName("is_ocr_manual_zoned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("Parents")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parents");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("int")
                        .HasColumnName("review_status");

                    b.Property<int>("SeparateTypeId")
                        .HasColumnType("int")
                        .HasColumnName("separate_type_id");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_stg_doc_types");

                    b.ToTable("stg_doc_types", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.StgDocTypeOcrFix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDoctype")
                        .HasColumnType("int")
                        .HasColumnName("id_doctype");

                    b.Property<int>("IdField")
                        .HasColumnType("int")
                        .HasColumnName("id_field");

                    b.Property<int>("IdOcrFix")
                        .HasColumnType("int")
                        .HasColumnName("id_ocr_fix");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_stg_doc_type_ocr_fixes");

                    b.ToTable("stg_doc_type_ocr_fixes", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.StgDocTypeSeparate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<int>("IdDoctype")
                        .HasColumnType("int")
                        .HasColumnName("id_doctype");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.Property<int>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_stg_doc_type_separates");

                    b.ToTable("stg_doc_type_separates", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.StgDocTypeSyncSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FixValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fix_value");

                    b.Property<int>("IType")
                        .HasColumnType("int")
                        .HasColumnName("i_type");

                    b.Property<int>("IdField")
                        .HasColumnType("int")
                        .HasColumnName("id_field");

                    b.Property<int>("IdFieldGroup")
                        .HasColumnType("int")
                        .HasColumnName("id_field_group");

                    b.Property<int>("IdPatternType")
                        .HasColumnType("int")
                        .HasColumnName("id_pattern_type");

                    b.Property<int>("IdType")
                        .HasColumnType("int")
                        .HasColumnName("id_type");

                    b.Property<bool>("IsCapitalize")
                        .HasColumnType("bit")
                        .HasColumnName("is_capitalize");

                    b.Property<bool>("IsCatalog")
                        .HasColumnType("bit")
                        .HasColumnName("is_catalog");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit")
                        .HasColumnName("is_read_only");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsUpperCase")
                        .HasColumnType("bit")
                        .HasColumnName("is_upper_case");

                    b.Property<int>("MaxLen")
                        .HasColumnType("int")
                        .HasColumnName("max_len");

                    b.Property<string>("MaxValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("max_value");

                    b.Property<int>("MinLen")
                        .HasColumnType("int")
                        .HasColumnName("min_len");

                    b.Property<string>("MinValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("min_value");

                    b.Property<string>("PatternCustom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pattern_custom");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_stg_doc_type_sync_settings");

                    b.ToTable("stg_doc_type_sync_settings", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.StgDocTypeSyncType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("describe");

                    b.Property<int>("DocTypeId")
                        .HasColumnType("int")
                        .HasColumnName("doc_type_id");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("format");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("ScanPathRoot")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scan_path_root");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_stg_doc_type_sync_types");

                    b.ToTable("stg_doc_type_sync_types", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.StgPatternType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_stg_pattern_types");

                    b.ToTable("stg_pattern_types", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
