// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SHTL.Modules.Infrastructure.Persistence;

#nullable disable

namespace SHTL.Modules.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502093345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Acc.Dept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int")
                        .HasColumnName("channel_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("describe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Parent")
                        .HasColumnType("int")
                        .HasColumnName("parent");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("Parents")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parents");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_acc_depts");

                    b.ToTable("acc_depts", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Acc.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int")
                        .HasColumnName("channel_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("module_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Parent")
                        .HasColumnType("int")
                        .HasColumnName("parent");

                    b.Property<string>("Parents")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parents");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_acc_roles");

                    b.ToTable("acc_roles", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Acc.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_acc_users");

                    b.ToTable("acc_users", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Acc.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int")
                        .HasColumnName("channel_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_acc_user_roles");

                    b.ToTable("acc_user_roles", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Cnf.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountLimit")
                        .HasColumnType("int")
                        .HasColumnName("account_limit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("describe");

                    b.Property<long>("DocumentLimit")
                        .HasColumnType("bigint")
                        .HasColumnName("document_limit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("is_published");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lang");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Parent")
                        .HasColumnType("int")
                        .HasColumnName("parent");

                    b.Property<string>("Parents")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parents");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<long>("StorageLimit")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_limit");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_cnf_channels");

                    b.ToTable("cnf_channels", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("author");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int")
                        .HasColumnName("channel_id");

                    b.Property<DateTime?>("Checked1At")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked1at");

                    b.Property<int>("Checked1By")
                        .HasColumnType("int")
                        .HasColumnName("checked1by");

                    b.Property<byte>("Checked1Result")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked1result");

                    b.Property<int>("Checked1ReturnCount")
                        .HasColumnType("int")
                        .HasColumnName("checked1return_count");

                    b.Property<string>("Checked1ReturnReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("checked1return_reason");

                    b.Property<DateTime?>("Checked2At")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked2at");

                    b.Property<int>("Checked2By")
                        .HasColumnType("int")
                        .HasColumnName("checked2by");

                    b.Property<byte>("Checked2Result")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked2result");

                    b.Property<string>("Checked2ReturnReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("checked2return_reason");

                    b.Property<DateTime?>("CheckedFinalAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked_final_at");

                    b.Property<int>("CheckedFinalBy")
                        .HasColumnType("int")
                        .HasColumnName("checked_final_by");

                    b.Property<string>("CheckedFinalChangeInfo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("checked_final_change_info");

                    b.Property<byte>("CheckedFinalResult")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked_final_result");

                    b.Property<DateTime?>("CheckedLogicAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked_logic_at");

                    b.Property<int>("CheckedLogicBy")
                        .HasColumnType("int")
                        .HasColumnName("checked_logic_by");

                    b.Property<byte>("CheckedLogicResult")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked_logic_result");

                    b.Property<DateTime?>("CheckedScan1At")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked_scan1at");

                    b.Property<int>("CheckedScan1By")
                        .HasColumnType("int")
                        .HasColumnName("checked_scan1by");

                    b.Property<byte>("CheckedScan1Result")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked_scan1result");

                    b.Property<DateTime?>("CheckedScan2At")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked_scan2at");

                    b.Property<int>("CheckedScan2By")
                        .HasColumnType("int")
                        .HasColumnName("checked_scan2by");

                    b.Property<byte>("CheckedScan2Result")
                        .HasColumnType("tinyint")
                        .HasColumnName("checked_scan2result");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("content_type_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<byte>("CurrentStep")
                        .HasColumnType("tinyint")
                        .HasColumnName("current_step");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("describe");

                    b.Property<int>("DocTypeId")
                        .HasColumnType("int")
                        .HasColumnName("doc_type_id");

                    b.Property<long>("ExcelMetadataId")
                        .HasColumnType("bigint")
                        .HasColumnName("excel_metadata_id");

                    b.Property<byte>("ExportStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("export_status");

                    b.Property<DateTime?>("ExportedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("exported_at");

                    b.Property<int>("ExportedBy")
                        .HasColumnType("int")
                        .HasColumnName("exported_by");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extension");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("extracted_at");

                    b.Property<int>("ExtractedBy")
                        .HasColumnType("int")
                        .HasColumnName("extracted_by");

                    b.Property<byte>("ExtractedResult")
                        .HasColumnType("tinyint")
                        .HasColumnName("extracted_result");

                    b.Property<int>("ExtractedReturnCount")
                        .HasColumnType("int")
                        .HasColumnName("extracted_return_count");

                    b.Property<string>("ExtractedReturnReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extracted_return_reason");

                    b.Property<string>("Field1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field1");

                    b.Property<string>("Field10")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field10");

                    b.Property<string>("Field11")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field11");

                    b.Property<string>("Field12")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field12");

                    b.Property<string>("Field13")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field13");

                    b.Property<string>("Field14")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field14");

                    b.Property<string>("Field15")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field15");

                    b.Property<long?>("Field16")
                        .HasColumnType("bigint")
                        .HasColumnName("field16");

                    b.Property<long?>("Field17")
                        .HasColumnType("bigint")
                        .HasColumnName("field17");

                    b.Property<long?>("Field18")
                        .HasColumnType("bigint")
                        .HasColumnName("field18");

                    b.Property<long?>("Field19")
                        .HasColumnType("bigint")
                        .HasColumnName("field19");

                    b.Property<string>("Field2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field2");

                    b.Property<long?>("Field20")
                        .HasColumnType("bigint")
                        .HasColumnName("field20");

                    b.Property<DateTime?>("Field21")
                        .HasColumnType("datetime2")
                        .HasColumnName("field21");

                    b.Property<DateTime?>("Field22")
                        .HasColumnType("datetime2")
                        .HasColumnName("field22");

                    b.Property<decimal?>("Field23")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("field23");

                    b.Property<decimal?>("Field24")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("field24");

                    b.Property<decimal?>("Field25")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("field25");

                    b.Property<string>("Field3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field3");

                    b.Property<string>("Field4")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field4");

                    b.Property<string>("Field5")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field5");

                    b.Property<string>("Field6")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field6");

                    b.Property<string>("Field7")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field7");

                    b.Property<string>("Field8")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field8");

                    b.Property<string>("Field9")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field9");

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<long>("FolderId")
                        .HasColumnType("bigint")
                        .HasColumnName("folder_id");

                    b.Property<bool>("IsChecked1")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked1");

                    b.Property<bool>("IsChecked2")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked2");

                    b.Property<bool>("IsCheckedFinal")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked_final");

                    b.Property<bool>("IsCheckedLogic")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked_logic");

                    b.Property<bool>("IsCheckedScan1")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked_scan1");

                    b.Property<bool>("IsCheckedScan2")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked_scan2");

                    b.Property<bool>("IsColorScan")
                        .HasColumnType("bit")
                        .HasColumnName("is_color_scan");

                    b.Property<bool>("IsExtracted")
                        .HasColumnType("bit")
                        .HasColumnName("is_extracted");

                    b.Property<bool>("IsOcrEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_ocr_enabled");

                    b.Property<bool>("IsZoned")
                        .HasColumnType("bit")
                        .HasColumnName("is_zoned");

                    b.Property<DateTime?>("Issued")
                        .HasColumnType("datetime2")
                        .HasColumnName("issued");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("issued_by");

                    b.Property<int?>("IssuedYear")
                        .HasColumnType("int")
                        .HasColumnName("issued_year");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("locked_at");

                    b.Property<byte>("LockedByStep")
                        .HasColumnType("tinyint")
                        .HasColumnName("locked_by_step");

                    b.Property<int>("LockedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("locked_by_user_id");

                    b.Property<double>("MaxDpi")
                        .HasColumnType("float")
                        .HasColumnName("max_dpi");

                    b.Property<double>("MinDpi")
                        .HasColumnType("float")
                        .HasColumnName("min_dpi");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Noted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noted");

                    b.Property<DateTime?>("OcrAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ocr_at");

                    b.Property<int>("OcrBy")
                        .HasColumnType("int")
                        .HasColumnName("ocr_by");

                    b.Property<byte>("OcrResult")
                        .HasColumnType("tinyint")
                        .HasColumnName("ocr_result");

                    b.Property<byte>("OcrStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("ocr_status");

                    b.Property<int>("PageCount")
                        .HasColumnType("int")
                        .HasColumnName("page_count");

                    b.Property<int>("PageCountA0")
                        .HasColumnType("int")
                        .HasColumnName("page_count_a0");

                    b.Property<int>("PageCountA1")
                        .HasColumnType("int")
                        .HasColumnName("page_count_a1");

                    b.Property<int>("PageCountA2")
                        .HasColumnType("int")
                        .HasColumnName("page_count_a2");

                    b.Property<int>("PageCountA3")
                        .HasColumnType("int")
                        .HasColumnName("page_count_a3");

                    b.Property<int>("PageCountA4")
                        .HasColumnType("int")
                        .HasColumnName("page_count_a4");

                    b.Property<int>("PageCountOther")
                        .HasColumnType("int")
                        .HasColumnName("page_count_other");

                    b.Property<string>("PathConverted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path_converted");

                    b.Property<string>("PathOriginal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path_original");

                    b.Property<string>("PathPdfSearchable")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path_pdf_searchable");

                    b.Property<string>("RecordNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("record_no");

                    b.Property<int>("RecordTypeId")
                        .HasColumnType("int")
                        .HasColumnName("record_type_id");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<string>("Signer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("signer");

                    b.Property<string>("SortMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sort_meta");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<string>("SymbolNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symbol_no");

                    b.Property<int>("SyncTypeId")
                        .HasColumnType("int")
                        .HasColumnName("sync_type_id");

                    b.Property<string>("ThumbPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thumb_path");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<string>("VersionPdf")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("version_pdf");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.Property<string>("WorkstationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("workstation_name");

                    b.Property<DateTime?>("ZonedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("zoned_at");

                    b.Property<int>("ZonedBy")
                        .HasColumnType("int")
                        .HasColumnName("zoned_by");

                    b.Property<byte>("ZonedResult")
                        .HasColumnType("tinyint")
                        .HasColumnName("zoned_result");

                    b.HasKey("Id")
                        .HasName("pk_stg_documents");

                    b.ToTable("stg_documents", "dbo");
                });

            modelBuilder.Entity("SHTL.Modules.Core.Domain.Entities.Stg.ExportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int")
                        .HasColumnName("channel_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ExcelFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("excel_file_name");

                    b.Property<string>("ExcelFilePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("excel_file_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("JsonConfig")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("json_config");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("SearchMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("search_meta");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_cnf_export_types");

                    b.ToTable("cnf_export_types", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
